version: '3.8'

services:
  app:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      - DATABASE_URL=postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@db/$(POSTGRES_DB)
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  migrate:
    image: migrate/migrate
    volumes:
      - /home/admin123/Desktop/kbtu2_3semestr/GoLang/final_project/Golang-Final-Project/schema:/migrations
    command: ["-path", "/migrations", "-database", "postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}?sslmode=disable", "up" ]
    depends_on:
      - db
