---

services:
  app:
    image: prod-service:local
    container_name: ps-backend
    ports:
      - "8080:30000"
    depends_on:
      - postgresql
    networks:
      - ps


  postgresql:
    image: postgres:14-alpine
    container_name: ps-psql
    environment:
      - POSTGRES_DB=prodservice
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./data:/var/lib/postgresql/data
      -

networks:
  ps: